"""Sphinx configuration file. Adapted from Sphinx autogenerated conf.py."""

import os
import sys
sys.path.insert(0, os.path.abspath('..'))
sys.path.insert(0, os.path.abspath('../gander/'))
from gander import __version__, __authors__


project = 'Gander'
copyright = '2019, Ekkobit AS'
author = __authors__
release = __version__

extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.todo',
]

templates_path = ['_templates']

exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

html_theme = 'alabaster'
html_theme_options = {
    'logo': 'logo.svg',
    'github_user': 'ekkobit',
    'github_repo': 'gander',
}

html_static_path = ['source/static']

# Todos
todo_include_todos = True

# Math
# imgmath_image_format = 'svg'

# Setting the master file (toctree)
master_doc = 'index'
